### ISSUE TITLE
Uncaught internal server error

### ISSUE THREAD

**Issue by adamjanicki2** [ripplifyio/ripplifyio.github.io#3]
Not sure if this can be repro'd elsewhere, but on my machine I'm getting an internal server error from an api request, I think there just needs to be a catch clause [here](https://github.com/ripplifyio/ripplifyio.github.io/blob/main/src/services/API.js#L77) and that should probably fix it

<img width="706" alt="Screen Shot 2023-11-29 at 1 58 45 PM" src="https://github.com/ripplifyio/ripplifyio.github.io/assets/45052692/a9670e23-20c6-4342-ab87-5fcf8e9ab4b7">

**Comment by ErikBoesen** [comment]
This is something that probably should propagate to the front end. It's caused by Spotify denying authentication requests for users that don't have developer accounts (because I forgot that the app is in developer mode and I needed to apply for extended access). The application is submitted now, so hopefully they give approval soon. Thanks so much Adam!
